# Generated by Django 5.2.6 on 2025-10-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apartment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dor',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_num',
            field=models.TextField(),
        ),
    ]
