# Generated by Django 5.2.6 on 2025-09-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_text',
            field=models.TextField(blank=True),
        ),
    ]
